# Generated by Django 4.2.5 on 2023-09-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('quitado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.reserva')),
            ],
        ),
    ]
